stages:
  preprocess:
    cmd: python -m src.data_preprocessing
    deps:
      - src/data_preprocessing.py
      - data/raw
    outs:
      - data/processed

  train:
    cmd: python -m src.train
    deps:
      - src/train.py
      - src/model.py
      - data/processed
    outs:
      - models/model.pt
